all:
  children:
    postgres_ha:
      hosts:
        pg-node-1:
          ansible_host: 192.0.2.10
          etcd_name: node1
        pg-node-2:
          ansible_host: 192.0.2.11
          etcd_name: node2
        pg-node-3:
          ansible_host: 192.0.2.12
          etcd_name: node3
