all:
  children:
    postgres_ha:
      hosts:
        pg-node-1:
          ansible_host: 1.2.3.4
        pg-node-2:
          ansible_host: 1.2.3.5
        pg-node-3:
          ansible_host: 1.2.3.6
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_rsa