---
all:
  children:
    postgres_ha:
      hosts:
        pg-node-1:
          ansible_host: 178.154.253.190
        pg-node-2:
          ansible_host: 46.21.247.113
        pg-node-3:
          ansible_host: 178.154.252.184
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
